hello:
	echo "Hello World"
	echo "This line will print if the file hello does not exist."

# We have one target called 'hello'
# This target has two commands
# This target has no prerequisites

# We'll then urn make hello. As long as the hello file does not exist, the commands will run. If hello does exist, no commands will run.

# We're talking about hello as both a target and a file
# The two are directoly tied together
# When a target is run aka when the commands
# of a target are run - the commands will create a file
# With the same name as the target

# In this case hello target does not create the hello file